application:
  security:
    jwt:
      secret:
        key: ${JWT_SECRET}

spring:
  data:
    mongodb:
      uri: ${DATABASE_URI}
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      charset: UTF-8

cors:
  allowed:
    methods: PUT, POST, GET, DELETE
  maxAge: 3600