CREATE DATABASE proyectohoteles DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE huesped (
    idHuesped BIGINT NOT NULL AUTO_INCREMENT,
    NumDocHues DOUBLE NOT NULL,
    Tipo_Doc_Hues VARCHAR(100) NOT NULL,
    Pais_Emisor VARCHAR(100) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Apellido1 VARCHAR(100) NOT NULL,
    Apellido2 VARCHAR(100) NOT NULL,
    Fecha_Nac_Hues DATE NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Dirreccion VARCHAR(100) NOT NULL,
    Categoria_Hues VARCHAR(100) NOT NULL,
    PRIMARY KEY (idHuesped)
)
Engine=InnoDB
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE personal (
    IdPersonal BIGINT NOT NULL AUTO_INCREMENT,
    NumDocPer DOUBLE NOT NULL,
    Tipo_Documento VARCHAR(100) NOT NULL,
    Pais_Emisor VARCHAR(100) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Apellido1 VARCHAR(100) NOT NULL,
    Apellido2 VARCHAR(100) NOT NULL,
    Fecha_Nac_Per DATE NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Dirrecion VARCHAR(100) NOT NULL,
    Cargo VARCHAR(100) NOT NULL,
    IDSEDE BIGINT NOT NULL,
    PRIMARY KEY (IdPersonal)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE Reserva (
    IdReserva BIGINT NOT NULL AUTO_INCREMENT,
    IDHUESPED BIGINT NOT NULL,
    FechaDesde DATE NOT NULL,
    FechaFin DATE NOT NULL,
    Total_Pago DOUBLE NOT NULL,
    Estado_Reserva VARCHAR(100) NOT NULL,
    PRIMARY KEY (IdReserva)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE HotelSede (
    IdSede BIGINT NOT NULL AUTO_INCREMENT,
    Nom_Sede VARCHAR(100) NOT NULL,
    Dirrecion VARCHAR(100) NOT NULL,
    PRIMARY KEY (IdSede)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE Habitacion (
    IdHabitacion BIGINT NOT NULL AUTO_INCREMENT,
    IDSEDE BIGINT NOT NULL,
    IDTIPOHABITACION BIGINT NOT NULL,
    PRIMARY KEY (IdHabitacion)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE TipoHabitacion (
    IdTipoHabitacion BIGINT NOT NULL AUTO_INCREMENT,
    TipoHab VARCHAR(100) NOT NULL,
    PrecioHab DOUBLE NOT NULL,
    Descripcion TEXT NOT NULL,
    PRIMARY KEY (IdTipoHabitacion)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE Salon (
    IdSalon BIGINT NOT NULL AUTO_INCREMENT,
    IDSEDE BIGINT NOT NULL,
    IDTIPOSALON BIGINT NOT NULL,
    Detalle TEXT NOT NULL,
    PRIMARY KEY (IdSalon)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE TipoSalon (
    IdTipoSalon BIGINT NOT NULL AUTO_INCREMENT,
    TipoSalon VARCHAR(100) NOT NULL,
    PrecioSalon DOUBLE NOT NULL,
    Descripcion TEXT NOT NULL,
    PRIMARY KEY (IdTipoSalon)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE TipoPago (
    IdTipoPago BIGINT NOT NULL AUTO_INCREMENT,
    TipoPago VARCHAR(100) NOT NULL,
    PRIMARY KEY (IdTipoPago)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE UserPass (
    IdUser BIGINT NOT NULL AUTO_INCREMENT,
    Usuario VARCHAR(100) NOT NULL,
    Contraseña VARCHAR(100) NOT NULL,
    PRIMARY KEY (IdUser)
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

 CREATE TABLE SalReser (
    IDSALON BIGINT NOT NULL,
    IDRESERVA BIGINT NOT NULL,
    NumAsistentes DOUBLE NOT NULL,
    CheckIn DATE NOT NULL,
    CheckOut DATE NOT NULL,
    DetalleConsumo TEXT NOT NULL,
    TotalConsumo DOUBLE NOT NULL,
    Estado VARCHAR(100) NOT NULL,
    Osbservaciones TEXT NOT NULL
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE ReservaTPago (
    IDRESERVA BIGINT NOT NULL,
    IDTIPOPAGO BIGINT NOT NULL,
    Observaciones TEXT NOT NULL
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE HabitReser (
    IDHABITACION BIGINT NOT NULL,
    IDRESERVA BIGINT NOT NULL,
    NumPersonas DOUBLE NOT NULL,
    CheckIn DATE NOT NULL,
    CheckOut DATE NOT NULL,
    DetalleConsumo TEXT NOT NULL,
    TotalConsumo DOUBLE NOT NULL,
    Observaciones TEXT NOT NULL
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE TelPersonal (
    IDPERSONAL BIGINT NOT NULL,
    PaisPrefijoEmisor VARCHAR(100) NOT NULL,
    NumTelefono DOUBLE NOT NULL
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE TelHuesped (
    IDHUESPED BIGINT NOT NULL,
    PaisEmisor VARCHAR(100),
    NumTelefono DOUBLE NOT NULL
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE Calificacion (
    IDHUESPED BIGINT NOT NULL,
    Estrellas INT NOT NULL,
    Descripcion TEXT NOT NULL
)
Engine=Innodb
DEFAULT CHARACTER SET utf8mb4;


ALTER TABLE Calificacion
ADD CONSTRAINT Calificacion_ibft FOREIGN KEY (IDHUESPED) REFERENCES Huesped(IdHuesped) ON UPDATE CASCADE;

ALTER TABLE TelHuesped
ADD CONSTRAINT TelHuespef_ibft FOREIGN KEY (IDHUESPED) REFERENCES Huesped(IdHuesped) ON UPDATE CASCADE;

ALTER TABLE Reserva
ADD CONSTRAINT Reserva_ibft FOREIGN KEY (IDHUESPED) REFERENCES Huesped(IdHuesped) ON UPDATE CASCADE;
 
ALTER TABLE ReservaTPago
ADD CONSTRAINT ReservaTPago_ibft1 FOREIGN KEY (IDRESERVA) REFERENCES Reserva(IdReserva) ON UPDATE CASCADE,
ADD CONSTRAINT ReservaTPago_ibft2 FOREIGN KEY (IDTIPOPAGO) REFERENCES TipoPago(IdTipoPago) ON UPDATE CASCADE;

ALTER TABLE HabitReser
ADD CONSTRAINT HabitReser_ibft1 FOREIGN KEY (IDRESERVA) REFERENCES Reserva(IdReserva) ON UPDATE CASCADE,
ADD CONSTRAINT HabitReser_ibft2 FOREIGN KEY (IDHABITACION) REFERENCES Habitacion(IdHabitacion) ON UPDATE CASCADE;

ALTER TABLE SalReser 
ADD CONSTRAINT SalReser_ibft1 FOREIGN KEY (IDRESERVA) REFERENCES Reserva(IdReserva) ON UPDATE CASCADE,
ADD CONSTRAINT SalReser_ibft2 FOREIGN KEY (IDSALON) REFERENCES Salon(IdSalon) ON UPDATE CASCADE;

ALTER TABLE Salon 
ADD CONSTRAINT Salon_ibft1 FOREIGN KEY (IDSEDE) REFERENCES HotelSede(IdSede) ON UPDATE CASCADE,
ADD CONSTRAINT Salon_ibft2 FOREIGN KEY (IDTIPOSALON) REFERENCES TipoSalon(IdTipoSalon) ON UPDATE CASCADE;

ALTER TABLE Habitacion
ADD CONSTRAINT Habitacion_ibft1 FOREIGN KEY (IDTIPOHABITACION) REFERENCES TipoHabitacion(IdTipoHabitacion) ON UPDATE CASCADE,
ADD CONSTRAINT Habitacion_ibft2 FOREIGN KEY (IDSEDE) REFERENCES HotelSede(IdSede) ON UPDATE CASCADE;

ALTER TABLE Personal
ADD CONSTRAINT Personal_ibft FOREIGN KEY (IDSEDE) REFERENCES HotelSede(IdSede) ON UPDATE CASCADE;

ALTER TABLE TelPersonal 
ADD CONSTRAINT TelPersonal_ibft FOREIGN KEY (IDPERSONAL) REFERENCES Personal(IdPersonal) ON UPDATE CASCADE;


